name: Create a release

on:
  release:
    types: [created]

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: false


jobs:
  package-rpm:
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build RPM package
      run: nix build -L '.#minuska-bundle-rpm' --out-link './result-minuska-rpm'
    - name: Upload .rpm package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ vars.PKG_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm
        path: ./result-minuska-rpm/*.rpm


  package-deb:
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build DEB package
      run: nix build -L '.#minuska-bundle-deb' --out-link './result-minuska-deb'
    - name: Upload .deb package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ vars.PKG_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.deb
        path: ./result-minuska-deb/*.deb
        
  package-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Docker image
        run: nix build -L '.#minuska-docker' --out-link ./result-minuska-docker
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.PKG_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}-docker.tar.gz
          path: ./result-minuska-docker
          
  release:
    #if: github.ref == 'refs/heads/main'
    name: Create release with all assets
    needs: [package-rpm, package-deb, package-docker]
    runs-on: ubuntu-latest
    steps:
      - name: Download cached rpm, deb, and tar.gz artifacts
        uses: actions/download-artifact@v3

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ vars.PKG_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.rpm/**/*.rpm
            ${{ vars.PKG_NAME }}-${{ github.ref_name }}-1.${{ env.DIST }}.${{ env.ARCH }}.deb/**/*.deb
            */*-docker.tar.gz
