name: Create a release

on:
  release:
    types: [created]

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: false


jobs:
  package-rpm:
    #if: github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build RPM package
      run: nix build -L '.#minuska-bundle-rpm' --out-link './result-minuska-rpm'
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          result-minuska-rpm/*.rpm

  package-deb:
    #if: github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build DEB package
      run: nix build -L '.#minuska-bundle-deb' --out-link './result-minuska-deb'
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          result-minuska-deb/*.deb
        
  package-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Docker image
        run: nix build -L '.#minuska-docker' --out-link ./result-minuska-docker
      - name: Rename the image
        run: mv ./result-minuska-docker minuska-${{runner.arch}}-docker.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            minuska-*-docker.tar.gz

